-- Space Cargo Stowage — initial schema
-- Portable DDL: runs on PostgreSQL (prod) and H2 in PostgreSQL mode (tests).

CREATE TABLE containers (
    container_id VARCHAR(64)  PRIMARY KEY,
    zone         VARCHAR(128) NOT NULL,
    width        DOUBLE PRECISION NOT NULL CHECK (width  > 0),
    depth        DOUBLE PRECISION NOT NULL CHECK (depth  > 0),
    height       DOUBLE PRECISION NOT NULL CHECK (height > 0),
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE items (
    item_id                VARCHAR(64) PRIMARY KEY,
    name                   VARCHAR(255) NOT NULL,
    dimension_w            DOUBLE PRECISION NOT NULL CHECK (dimension_w > 0),
    dimension_d            DOUBLE PRECISION NOT NULL CHECK (dimension_d > 0),
    dimension_h            DOUBLE PRECISION NOT NULL CHECK (dimension_h > 0),
    mass                   DOUBLE PRECISION CHECK (mass >= 0),
    priority               INTEGER NOT NULL CHECK (priority BETWEEN 0 AND 100),
    expiry_date            DATE,
    usage_limit            INTEGER,
    remaining_uses         INTEGER,
    preferred_zone         VARCHAR(128),
    preferred_container_id VARCHAR(64),
    status                 VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Location (populated only when stowed)
    container_id           VARCHAR(64),
    position_x             DOUBLE PRECISION,
    position_y             DOUBLE PRECISION,
    position_z             DOUBLE PRECISION,
    placed_dimension_w     DOUBLE PRECISION,
    placed_dimension_d     DOUBLE PRECISION,
    placed_dimension_h     DOUBLE PRECISION,

    CONSTRAINT fk_items_container
        FOREIGN KEY (container_id) REFERENCES containers (container_id)
        ON DELETE SET NULL
);

CREATE TABLE action_logs (
    log_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id      VARCHAR(128),
    action_type  VARCHAR(64) NOT NULL,
    item_id      VARCHAR(64),
    details_json TEXT
);

CREATE INDEX idx_items_status       ON items (status);
CREATE INDEX idx_items_container_id ON items (container_id);
CREATE INDEX idx_logs_action_type   ON action_logs (action_type);
CREATE INDEX idx_logs_timestamp     ON action_logs (timestamp);
CREATE INDEX idx_logs_item_id       ON action_logs (item_id);
